server:
  port: 8005
spring:
  application:
    name: service-carro
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 
